#+title: Econometría Aplicada. Criterios de evaluación
# +author: Basado en las instrucciones de la Profesora Lola Robles
#+LANGUAGE: es
#+OPTIONS: author:nil
#+OPTIONS: toc:nil

# ###########
# ESTO DA EL FORMATO FINAL DE LA PÁGINA WEB VÉASE [[https://olmon.gitlab.io/org-themes/]]
# +SETUPFILE: ./css/readtheorg_inline.theme
# ###########

#+LATEX_HEADER: \usepackage{fullpage}
#+LATEX_HEADER: \usepackage{rotating}

#+LATEX: \maketitle

- Examen final (60%) 

- Tareas de evaluación continua (40%)

  + Pruebas parciales (controles intermedios) (20%)

    - Prueba 1 con Marcos Bujosa
    - Prueba 2 con David Guerrero

  + Prácticas y trabajo de clase (20%)

    - Trabajo empírico y evaluación por pares
    - Prácticas/ejercicios para casa
    - Test realizados en clase

Para obtener la calificación de *no presentado* basta con no realizar el examen final.

* Trabajo empírico con evaluación por pares

Los trabajos empíricos se llevarán a cabo en grupos de dos personas (Tarea 1). 
Las evaluaciones de trabajos de compañeros serán individuales (Tarea 2).
Ambas tareas tienen la misma importancia:

- Tarea 1 (en grupo) :: /Elaboración de un trabajo empírico/. En esta tarea se analizarán datos reales con las técnicas econométricas vistas en clase.

- Tarea 2 (individual) :: /Evaluación por pares/. Cada alumno deberá evaluar cinco de los trabajos elaborados en la Tarea 1 (distintos del suyo).

#+BEGIN_QUOTE
/El material necesario para la elaboración del trabajo empírico se entregará a través del Campus Virtual al finalizar la teoría correspondiente necesaria para poder realizarlo. También en ese momento se determinarán las fechas clave para la entrega del proyecto en sus distintas etapas./
#+END_QUOTE


** Descripción general 

Este proyecto tiene un objetivo doble: 

- Poner en práctica las herramientas de análisis econométrico para dar respuesta a cuestiones relevantes y presentar los resultados en un informe profesional. 
- Desarrollar la capacidad crítica (y autocrítica) evaluando trabajos de terceros.

El alumno debe demostrar que sabe construir modelos ARIMA univariantes por medio de la metodología de Box-Jenkins (identificación, estimación, validación, previsiones puntuales e intervalos).

Cada alumno evaluará cinco trabajos (distintos al suyo) siguiendo la /Tabla de elementos a valorar/ (ver más abajo).

Cada grupo, tras recibir la evaluación de sus compañeros, podrá introducir mejoras en el trabajo conforme a los comentarios recibidos (si el grupo lo estima oportuno) con el fin de obtener una calificación final más alta.
La versión final será evaluada por el profesor.

** Tarea 1: Trabajo empírico conjunto

Se deberá elaborar un documento en formato PDF que incluya tablas, gráficos y análisis, acompañados de sus respectivas interpretaciones económicas. Este documento comenzará con una introducción que describa el objetivo general de la práctica y los datos utilizados. A continuación, se presentará una sección de resultados en la que se expondrán los análisis correspondientes a las distintas fases, debidamente comentados. El documento concluirá con una sección de conclusiones que evaluará el grado de cumplimiento de los objetivos, las implicaciones de los resultados obtenidos, las limitaciones encontradas que no se han podido resolver y las posibles extensiones del análisis realizado.

Documentos a entregar a través de la aplicación abierta específicamente para ello en el campus virtual:
- Informe del trabajo :: en formato PDF con: 
  - Introducción :: objetivo general y datos utilizados. 
  - Resultados :: análisis de las distintas fases con comentarios. 
  - Conclusiones :: cumplimiento de objetivos, implicaciones, limitaciones y posibles extensiones.
- Archivos auxiliares :: archivos GRETL con los análisis (preferiblemente como un guion ejecutable que permita reproducir los resultados).

** Tarea 2: Valoraciones individuales de trabajos de terceros

- Evaluación de 5 proyectos asignados mediante la aplicación de Moodle. 
- Uso de la matriz de elementos del informe a evaluar (/Tabla de elementos a valorar/). 
- Inclusión de observaciones y retroalimentación.

En esta valoración, quien evalúa debe identificar tanto las debilidades como los aspectos positivos y las áreas de mejora del trabajo analizado, con el objetivo de contribuir a la calidad final del proyecto evaluado. Cada estudiante recibirá cinco proyectos asignados para evaluación a través de la aplicación de Moodle. Posteriormente, también a través de la misma aplicación, deberá llevar a cabo la evaluación utilizando una matriz de rúbricas similar a la de la Tabla 1, que estará disponible en dicha plataforma.

Además de completar esta tabla, se deben incluir observaciones sobre la evaluación realizada (retroalimentación). Para ello, se seguirá el esquema y el guion descriptivo que se le proporcionará cuando se le entregue el material necesario para la elaboración de la práctica. Estas observaciones deben ofrecer una valoración general del trabajo, así como comentarios y sugerencias que identifiquen las áreas de mejora, los puntos fuertes y las carencias del trabajo evaluado.


** Calificación final del proyecto

La calificación será la media aritmética de las notas de las Tareas 1 y 2.

*** Criterios para Tarea 1 

1. Calificaciones de los evaluadores (supervisadas por el profesor, que penalizará que se otorguen calificaciones injustas por ser injustificadamente altas o bajas).
   - Si el autor de la Tarea 1 no está de acuerdo con alguna de las calificaciones o comentarios recibidos, podrá solicitar al profesor una revisión de la calificación. Esta solicitud también se considerará en la calificación final del proyecto.
   - El profesor penalizará severamente aquellos casos en los que se entregue un primer borrador que esté lejos del mínimo exigible.
2. Calidad de la versión final (se tendrá en cuenta el grado en que los autores han sido capaces de mejorar el trabajo considerando los comentarios recibidos por sus evaluadores).

*** Criterios para la Tarea 2

1. La adecuación de la calificación en relación con la calidad del trabajo evaluado.
2. La calidad del documento de evaluación, sus fortalezas y las sugerencias de mejora. Se aplicará una penalización significativa si no se presenta este documento o si este no resulta útil para el autor de la tarea evaluada.

** Observaciones 

1. La matriz de elementos a valorar también debe tenerse en cuenta al desarrollar la Tarea 1. 
2. Es importante plantear críticas, resaltar puntos fuertes y sugerir mejoras. 
3. Las valoraciones deben ser objetivas.

#+NAME: Matriz de elementos a valorar
#+ATTR_LATEX: :align p{.2cm}p{7cm}|p{1.5cm}p{3cm}p{4.2cm}p{4cm}  :float sideways
|    | Elemento a valorar                                |            |                               |                                           |                            |
|----+---------------------------------------------------+------------+-------------------------------+-------------------------------------------+----------------------------|
|  1 | Introducción: planteamiento del problema          | Ausente    | No se entiende                | Se entiende con errores importantes       | Queda perfectamente claro  |
|  2 | Introducción: descripción de los datos            | Ausente    | No se entiende                | Se entiende con errores importantes       | Queda perfectamente claro  |
|  3 | Resultados: fase de identificación                | Ausente    | Empleo escaso de herramientas | Emplea la mayoría de herramientas         | Usa todas las herramientas |
|  4 | Resultados: interpretación identificación         | Ausente    | No se entiende                | Se entiende con errores importantes       | Queda perfectamente claro  |
|  5 | Resultados: estimación del modelo inicial         | Ausente    | Modelo incorrecto             | Identificado sin suficiente justificación | Modelo totalmente adecuado |
|  6 | Resultados: fase de validación                    | Ausente    | Pocos contrastes              | Mayoría de contrastes                     | Todos los contrastes       |
|  7 | Resultados: interpretación económica y contrastes | Ausente    | No se entiende                | Se entiende con errores importantes       | Queda perfectamente claro  |
|  8 | Resultados: previsión                             | Ausente    | Pocos análisis                | Mayoría de análisis                       | Previsión correcta         |
|  9 | Conclusiones: relación con objetivos              | Ausente    | No se entiende                | Se entiende con errores importantes       | Queda perfectamente claro  |
| 10 | Conclusiones: limitaciones y extensiones          | Ausente    | No se entiende                | Se entiende con errores importantes       | Queda perfectamente claro  |
| 11 | Cuestiones formales (paginación, tablas, etc.)    | Ninguna    | Solo algunas                  | Mayoría con errores                       | Todo correcto              |
| 12 | Valoración global                                 | Inadecuado | Errores importantes           | Aceptable con errores menores             | Bien ejecutado             |
|----+---------------------------------------------------+------------+-------------------------------+-------------------------------------------+----------------------------|

