#+TITLE: Publicación de los ficheros org en GitHub pages
#+author: Marcos Bujosa
#+LANGUAGE: es

# +OPTIONS: toc:nil

#+TAGS: noexport
#+EXCLUDE_TAGS: noexport

#+startup: shrink

# ###########
# ESTO DA EL FORMATO FINAL DE LA PÁGINA WEB VÉASE [[https://olmon.gitlab.io/org-themes/]]
#+SETUPFILE: ../css/readtheorg_inline.theme
# ###########

#+LATEX_HEADER_EXTRA: \usepackage{fullpage}


#+LATEX_HEADER_EXTRA: \usepackage[spanish]{babel}
#+LATEX_HEADER_EXTRA: \usepackage{lmodern}
#+LATEX_HEADER_EXTRA: \usepackage{tabularx}
#+LATEX_HEADER_EXTRA: \usepackage{booktabs}

#+BEGIN_SRC emacs-lisp :exports none :results silent :tangle no :eval yes
(unless (file-directory-p "docs")
  (make-directory "docs"))
(unless (file-directory-p "docs/.binder")
  (make-directory "docs/.binder"))
#+END_SRC


#+LATEX: \maketitle

* Fichero =makefile=

Genera el directorio =docs= con los ficheros para GitPages con subdirectorios para los =CuadernosElectronicos=, =pdfs=, =Transparencias= y los ficheros con las lecciones en ~html~.

#+BEGIN_SRC makefile :noweb no-export :results silent :tangle makefile
LECCIONES_SRC = ./org-lessons
LECCIONES_tmp = ./Lecciones-tmp
PRACTICAS_SRC = ./org-practicas
PRACTICAS_tmp = ./Practicas-tmp
DOCS = ./docs
CUADERNOS = $(DOCS)/CuadernosElectronicos
TRANSPARENCIAS = $(DOCS)/Transparencias

SRC_FILES = $(LECCIONES_SRC)/*.org
# SRC_FILES = $(LECCIONES_SRC)/Lecc*.org
# SRC_PRACTICAS_PYTHON_FILES = $(LECCIONES_SRC)/P-L.org

#.PHONY: cleanAll directorios programas_de_python calendario notebooksYslides limpia_kernels_jupyter practicas publicacion limpia_kernels_jupyter

all: calendario notebooksYslides practicas  publicacion-lecciones publicacion-practicas publicacion limpia_kernels_jupyter

calendario: directorios $(DOCS)/Calendario-Econometria-Aplicada.pdf

REPO_URL = https://github.com/mbujosab/TimeSeriesData
DATOS_DIR = ./datos/
TEMP_DIR = ../TimeSeriesData_temp

copia_datos: $(DATOS_DIR)
	@echo "Clonando el repositorio $(REPO_URL) con profundidad 1..."
	# 1. Clonar el repositorio en un directorio temporal SEGURO
	@git clone --depth 1 $(REPO_URL) $(TEMP_DIR)
	@echo "Copiando archivos y directorios sin la extensión .org, .git o .projectile a $(DATOS_DIR) (manteniendo estructura)..."
	# 2. **CRÍTICO:** Bloque condicional de rsync con exclusiones mejoradas
	@if [ -d "$(TEMP_DIR)" ]; then \
		rsync -av \
			--exclude '*/.git*' \
			--exclude '*.org' \
			--exclude '.*' \
			--include '*/' \
			--include '*' \
			"$(TEMP_DIR)/" "$(DATOS_DIR)"; \
	else \
		echo "ERROR: Falló la clonación. Directorio fuente ($(TEMP_DIR)) no encontrado. NO se copió nada." 1>&2; \
	fi
	@echo "Limpiando directorio temporal..."
	# 3. Eliminar el directorio temporal clonado
	@rm -rf "$(TEMP_DIR)"
	@echo "Copia de archivos y estructura completada."

$(DATOS_DIR):
	@mkdir -p $(DATOS_DIR)


$(DOCS)/Calendario-Econometria-Aplicada.pdf:
	emacs --batch Calendario/README.org -l org -f org-babel-tangle
	cd Calendario && make Calendario-Econometria-Aplicada.pdf

publicacion:
	cp -a README.org  $(DOCS)
	mkdir -p $(DOCS)/Practicas-html/img
	find . -wholename $(LECCIONES_tmp)/P-L*.pdf -exec cp {} $(DOCS)/Practicas-pdf/ \;
	find . -wholename $(LECCIONES_tmp)/P-L*.html -exec cp {} $(DOCS)/Practicas-html/ \;
	cp -a $(DOCS)/Lecciones-html/img/P-L* $(DOCS)/Practicas-html/img/
	cp -a $(DOCS)/Lecciones-html/P-L*.html $(DOCS)/Practicas-html/
#	find $(DOCS)/Lecciones-html/img/ -maxdepth 1 -type d -name "P-L*" -exec cp -a {}  $(DOCS)/Practicas-html/img/ \;
#	find $(DOCS)


# Defino las rutas de origen y destino para mayor claridad
SRC_IMG = $(DOCS)/Lecciones-html/img/ 
DST_IMG = $(DOCS)/Practicas-html/img/

# Para crear los enlaces simbólicos de las prácticas en Python
img_symlink_files:
	files=$(shell find $(SRC_IMG) -name *.png); \
	for file in $$files; do \
		if [ -e "$$file" ]; then \
			base_name=$$(basename "$$file" .png); \
			echo "Procesando archivo: $$file"; \
			ln -snf ../$$file "$(DST_IMG)$$base_name.png"; \
			echo "Enlace creado: $(DST_IMG)$$base_name.png -> ../$$file"; \
		else \
			echo "Archivo: $$file no existe"; \
		fi; \
	done


publicacion-lecciones: $(patsubst $(LECCIONES_SRC)/%.org,$(CUADERNOS)/%.ipynb,$(wildcard $(SRC_FILES))) README.org index.org
	echo "FICHEROS EN CuadernosElectronicos y Transparencias?..."
	cp -a $(LECCIONES_tmp)/Lecc*.slides.html $(TRANSPARENCIAS)
	find . -wholename $(LECCIONES_tmp)/P-L*.slides.html -exec cp {} $(TRANSPARENCIAS)/ \;
#	#cp -a $(LECCIONES_tmp)/P-L*.slides.html $(TRANSPARENCIAS)
	ls $(CUADERNOS)
	ls $(TRANSPARENCIAS)
	echo "EJECUCIÓN DE publica.el..."
	emacs --batch \
	  --load ~/Software/scimax/init.el \
	  -l publica.el
	touch $@
#	echo "FICHEROS EN Docs?..."
#	find $(DOCS)/Lecciones-html
#	find $(DOCS)/Lecciones-pdf

publicacion-practicas: $(patsubst $(PRACTICAS_SRC)/%.org,$(CUADERNOS)/%.ipynb,$(wildcard $(SRC_FILES))) README.org index.org
	echo "EJECUCIÓN DE publica-practicas.el..."
	emacs --batch \
	  --load ~/Software/scimax/init.el \
	  -l publica-practicas.el
	echo "FICHEROS EN Docs?..."
	cp -a $(PRACTICAS_SRC)/LicenciaGuionesGretl/COPYING $(DOCS)/Practicas-html/guiones/
	touch $@
#	find $(DOCS)/Practicas-html
#	find $(DOCS)/Practicas-pdf

licencia: 
	cp -a $(PRACTICAS_SRC)/LicenciaGuionesGretl/COPYING $(DOCS)/Practicas-html/guiones/

notebooksYslides: $(patsubst $(LECCIONES_SRC)/%.org,$(CUADERNOS)/%.ipynb,$(wildcard $(SRC_FILES)))
	touch $@
#	pkill -f "python3 -m ipykernel_launcher"

$(CUADERNOS)/%.ipynb $(TRANSPARENCIAS)/%.slides.html: $(LECCIONES_SRC)/%.org
	make directorios
	make programas_de_python
#	make symlink_files
	cp -a $(LECCIONES_SRC)/*.bib $(LECCIONES_tmp)
	cp -a $< $(LECCIONES_tmp)
	echo "EJECUCION DEL NOTEBOOK DE ORG: $(LECCIONES_tmp)/$(@F:.ipynb=.org)..."
	emacs -Q -l ~/Software/scimax/init.el $(LECCIONES_tmp)/$(@F:.ipynb=.org) --batch --eval "(org-babel-execute-buffer)" --eval "(save-buffer)" --kill
	cp -a $(LECCIONES_tmp)/$(@F) $(CUADERNOS)
	echo "EJECUCION DEL NOTEBOOK DE JUPYTER..."
	jupyter nbconvert --execute --inplace $(LECCIONES_tmp)/$(@F) 
	echo "FICHEROS EN ./lecciones?..."
#	find $(LECCIONES_tmp)
	echo "FICHEROS EN ./docs/Lecciones-html/img?..."
	cp -a $(LECCIONES_tmp)/img $(DOCS)/Lecciones-html
#	find $(DOCS)/Lecciones-html/img
	echo "Contenido de img tras notebook:"
#	find $(LECCIONES_tmp)/img
	echo "COPIO LO QUE SE HA GENERADO (.ipynb sin ejecutar y las imágenes) A ./docs..."
	ln -snf -r $(DOCS)/Lecciones-html/img/ $(TRANSPARENCIAS)/
	ln -snf -r $(DOCS)/Lecciones-html/img/ $(CUADERNOS)/
#	# Ejecutar el notebook con jupyter nbconvert
	echo "CREACIÓN DE LAS SLIDES..."
	jupyter nbconvert --config mycfg-GitHubPages.py --to slides --reveal-prefix "https://unpkg.com/reveal.js@5.2.1" --execute $(LECCIONES_tmp)/$(@F) 
	echo "➡️ FICHEROS EN docs/ TRAS GENERAR SLIDES Y NOTEBOOKS DE JUPYTER..."
#	find $(DOCS)



# Define las rutas de origen y destino para mayor claridad
SRC_DIR_PRACTICAS =./org-practicas/     # ./org-practicas/
DST_DIR_PRACTICAS =./org-lessons/

# Para crear los enlaces simbólicos de las prácticas en Python
symlink_files:
	files=$(shell find $(SRC_DIR_PRACTICAS) -name *.txt); \
	for file in $$files; do \
		if [ -e "$$file" ]; then \
			base_name=$$(basename "$$file" .txt); \
			echo "Procesando archivo: $$file"; \
			ln -snf ../$$file "$(DST_DIR_PRACTICAS)$$base_name.org"; \
			echo "Enlace creado: $(DST_DIR_PRACTICAS)$$base_name.org -> ../$$file"; \
		else \
			echo "Archivo: $$file no existe"; \
		fi; \
	done



# Lista de archivos fuente .org en org-practicas
PRACTICAS_ORG = $(wildcard org-practicas/*.org)

# Ficheros .done como señal de que fueron tanglados
PRACTICAS_DONE = $(patsubst org-practicas/%.org, $(PRACTICAS_tmp)/%.done, $(PRACTICAS_ORG))

# Objetivo principal de las prácticas en Gretl
practicas: figuras_de_lecciones $(PRACTICAS_DONE)
	@echo "✅ Todas las prácticas actualizadas."

$(PRACTICAS_tmp)/%.done: org-practicas/%.org
	echo "➡️ Copiando y ejecutando $< ..."
	mkdir -p $(PRACTICAS_tmp)/guiones
	cp $< $(PRACTICAS_tmp)/
	mkdir -p $(PRACTICAS_tmp)/src
	cp $(LECCIONES_tmp)/src/*.py $(PRACTICAS_tmp)/src
	ln -snf -r $(LECCIONES_tmp)/datos $(PRACTICAS_tmp)/
	cp -a org-practicas/hansl.tex $(PRACTICAS_tmp)/
	echo "🧠 Ejecutando org-babel-tangle y eval..."
	set -e; \
	if emacs --batch \
	  --load ~/Software/scimax/init.el \
	  $(PRACTICAS_tmp)/$*.org \
	  --eval "(org-babel-execute-buffer)" \
	  --eval "(save-buffer)" \
	  --kill; then \
	    echo "✅ Correcto: $<"; \
	    touch $@; \
	else \
	    echo "❌ Error al procesar $<"; \
	    rm -f $@; \
	    exit 1; \
	fi
	echo "➡️ listado de ficheros en el subdirectorio guiones"
	ls -lR $(PRACTICAS_tmp)/guiones  # Debug para Actions

figuras_de_lecciones:
	cp -a $(LECCIONES_tmp)/img/lecc04/MA2roots.png $(PRACTICAS_tmp)/img/
	cp -a $(LECCIONES_tmp)/img/lecc04/ACF-MA1p.png $(PRACTICAS_tmp)/img/
	cp -a $(LECCIONES_tmp)/img/lecc05/ACF-AR1p.png $(PRACTICAS_tmp)/img/
	cp -a $(LECCIONES_tmp)/img/lecc05/AR2roots.png $(PRACTICAS_tmp)/img/
	cp -a $(LECCIONES_tmp)/img/lecc03/IBEX35.png   $(PRACTICAS_tmp)/img/
	cp -a $(LECCIONES_tmp)/img/lecc07/ACF-RW.png   $(PRACTICAS_tmp)/img/

ORG_FILES := $(wildcard $(LECCIONES_SRC)/src/*.org)
TMP_FILES := $(patsubst $(LECCIONES_SRC)/src/%.org, $(LECCIONES_tmp)/src/%.org, $(ORG_FILES))

programas_de_python: $(TMP_FILES)

$(LECCIONES_tmp)/src/%.org: $(LECCIONES_SRC)/src/%.org
	echo "INICIO $*.ipynb..."
	make directorios
	cp $< $(LECCIONES_tmp)/src/
	emacs -q --batch $(LECCIONES_tmp)/src/$*.org -l org -f org-babel-tangle
	cp -a $(LECCIONES_tmp)/src/$*.py $(CUADERNOS)/src/
	ln -sf -r $(CUADERNOS)/src/$*.py $(CUADERNOS)/
	emacs -Q -l ~/Software/scimax/init.el $(LECCIONES_tmp)/$(@F:.ipynb=.org) --batch --eval "(org-babel-execute-buffer)" --eval "(save-buffer)" --kill
	emacs -q --batch \
	  --load ~/Software/scimax/init.el \
	  --eval "(require 'ox-ipynb)" \
	  --eval "(ox-ipynb-export-org-file-to-ipynb-file \"$(LECCIONES_tmp)/src/$*.org\")"
	jupyter nbconvert --execute --inplace $(LECCIONES_tmp)/src/$*.ipynb
	jupyter nbconvert --config mycfg-GitHubPages.py --to slides --reveal-prefix "https://unpkg.com/reveal.js@5.2.1" --execute $(LECCIONES_tmp)/src/$*.ipynb
	jupyter nbconvert --execute --to html $(LECCIONES_tmp)/src/$*.ipynb
	cp -a $(LECCIONES_tmp)/src/$*.ipynb $(CUADERNOS)
	cp -a $(LECCIONES_tmp)/src/$*.slides.html $(TRANSPARENCIAS)
	cp -a $(LECCIONES_tmp)/src/$*.html $(DOCS)/Lecciones-html/src/
	echo "TERMINADO $*.ipynb..."

directorios:
	mkdir -v -p .github/workflows
	mkdir -v -p $(LECCIONES_tmp)/src
	mkdir -v -p $(LECCIONES_tmp)/img
	mkdir -v -p $(PRACTICAS_tmp)/img
	mkdir -v -p $(DOCS)/Lecciones-pdf
	mkdir -v -p $(DOCS)/.binder
	mkdir -v -p $(DOCS)/Lecciones-html/img
	mkdir -v -p $(DOCS)/Lecciones-html/src
	mkdir -v -p $(TRANSPARENCIAS)
	mkdir -v -p $(CUADERNOS)/src
	cp -a ./css $(LECCIONES_tmp)/
	cp -a ./datos $(LECCIONES_tmp)/
	cp -a ./datos $(DOCS)/
	cp -a ./org-lessons/00preambulo_lecciones.txt $(LECCIONES_tmp)/
	cp -a ./org-practicas/00preambulo_practicas.txt $(PRACTICAS_tmp)/
	cp -a ./figurasGretl $(LECCIONES_tmp)/img/
	touch directorios

clean:
	rm -r -f $(LECCIONES_tmp)
	rm -r -f $(PRACTICAS_tmp)

cleanAll: clean
	#find $(DOCS)/ -mindepth 1 ! -name 'README.org' ! -name '.binder' -exec rm -rf {} +
	rm -r -f $(DOCS)
	rm -f directorios
	rm -f series_formales
	rm -f publicacion-lecciones
	rm -f publicacion-practicas
	rm -f practicas
	rm -f notebooksYslides
	rm -f sitemap.org
	rm -r -f logs

limpia_kernels_jupyter:
	pkill -f "python3 -m ipykernel_launcher"
	# pkill -f "python3 -m ipykernel_launcher -f /home/marcos/.local/share/jupyter/runtime/kernel-.*\.json"

#+END_SRC

** Aclaraciones

El directorio =./Lecciones-tmp= es temporal (en el fichero ~makefile~ se hace referencia a él con =$(LECCIONES_tmp)=). En dicho directorio se ejecutan los notebooks. Los ficheros creados se copian en distintos subdirectorios del directorio de publicación =./docs= (en el fichero ~makefile~ es referenciado con =$(DOCS)= ). El subdirectorio =./docs= es el directorio de donde "cuelgan" las páginas web; dichas páginas se distribuyen desde la rama =gh-pages= del repositorio.


* Fichero =build.yml=

Contiene las instrucciones que ejecutará GitHub Actions en el repositorio cada vez que éste sea actualizado.

Usa el contenido (los ficheros fuente) de la rama =main= y copia los ficheros compilados en la raíz de la rama =gh-pages=. 
#+BEGIN_SRC yml :tangle .github/workflows/build.yml
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #- name: Checkout repository
    #  uses: actions/checkout@v3

    - name: Checkout del repositorio principal
      uses: actions/checkout@v4

    - name: Checkout del repositorio de datos
      uses: actions/checkout@v4
      with:
        repository: mbujosab/TimeSeriesData
        path: datos_temp

    - name: Borrar contenido antiguo del directorio datos
      run: |
        rm -rf datos/*

    - name: Copiar archivos del repositorio de datos al directorio datos
      run: |
        cp -r datos_temp/* datos/

    - name: Comprobar contenido de datos antes de seguir
      run: |
        echo "Contenido de datos:"
        ls -la datos

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git emacs pandoc aspell aspell-en aspell-es zip gretl wget
        pip install jupyter nbconvert

    - name: Crear carpeta e instalar la base de datos del Banco de España en Gretl
      run: |
        mkdir -p ~/.gretl/db
        cp -r datos/BaseDeDatosBdE/* ~/.gretl/db/

    - name: Install Python modules
      run: |
        pip install sympy numpy pandas matplotlib dataframe-image statsmodels seaborn scipy

    - name: Exportar backend matplotlib
      run: echo "MPLBACKEND=Agg" >> $GITHUB_ENV

    - name: Verify Jupyter Installation
      run: |
        jupyter kernelspec list

    - name: Install LaTeX
      run: |
        sudo apt-get install -y texlive  texlive-latex-recommended texlive-latex-extra  texlive-fonts-extra texlive-fonts-recommended texlive-xetex texlive-science python3-pygments texlive-lang-spanish texlive-bibtex-extra texlive-binaries texlive-extra-utils texlive-font-utils texlive-luatex texlive-xetex dvipng

    - name: Disable tlmgr (prevent accidental calls)
      run: sudo mv /usr/bin/tlmgr /usr/bin/tlmgr.disabled || true

    - name: Clone Scimax (pin to scimax 3.0 tag)
      run: |
        mkdir -p ~/Software
        git clone https://github.com/jkitchin/scimax.git ~/Software/scimax
        cd ~/Software/scimax
        # Checkout the v3.0 tag explicitly (creates a branch scimax-3.0)
        git fetch --tags
        git checkout -b scimax-3.0 tags/3.0

    - name: Download ox-ipynb.el (pinned to ef9ba54) 
      run: | 
        wget https://raw.githubusercontent.com/jkitchin/ox-ipynb/ef9ba54/ox-ipynb.el -O ~/Software/scimax/ox-ipynb.el

#    - name: Download ox-ipynb.el (match pinned scimax)
#      run: |
#        wget https://raw.githubusercontent.com/jkitchin/ox-ipynb/master/ox-ipynb.el -O ~/Software/scimax/ox-ipynb.el

#    - name: Install Emacs packages required by scimax and org-babel (s, dash, jupyter, org-ref, org-db)
#      run: |
#        emacs --batch \
#          --eval "(require 'package)" \
#          --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" \
#          --eval "(package-refresh-contents)" \
#          --eval "(package-install 's)" \
#          --eval "(package-install 'dash)" \
#          --eval "(package-install 'jupyter)" \
#          --eval "(package-install 'org-ref)" \
#          --eval "(package-install 'org-db)" \
#          --eval "(package-install 'ox-ipynb)" || true

#    - name: Clone Scimax
#       run: |
#         git clone https://github.com/jkitchin/scimax.git ~/Software/scimax

#    - name: Download ox-ipynb.el
#      run: |
#        wget https://raw.githubusercontent.com/jkitchin/ox-ipynb/master/ox-ipynb.el -O ~/Software/scimax/ox-ipynb.el

    - name: Install s.el and dash.el
      run: |
        emacs --batch --eval "(require 'package)" \
                      --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\"))" \
                      --eval "(package-refresh-contents)" \
                      --eval "(package-install 's)" \
                      --eval "(package-install 'dash)"

    - name: Create no-tlmgr.el
      run: |
        mkdir -p ~/.emacs.d
        echo "(setq system-packages-use-sudo nil)" > ~/.emacs.d/no-tlmgr.el
        echo "(setq TeX-install-font-lock nil)" >> ~/.emacs.d/no-tlmgr.el
        echo "(setq TeX-live-install-texmf nil)" >> ~/.emacs.d/no-tlmgr.el

    - name: Verify ox-ipynb Installation
      run: |
        emacs --batch \
              --eval "(add-to-list 'load-path \"~/Software/scimax/\")" \
              --eval "(dolist (dir (directory-files \"~/.emacs.d/elpa/\" t \"^[^.]\")) (add-to-list 'load-path dir))" \
              --eval "(require 'ox-ipynb)"

    - name: Create .binder directory
      run: mkdir -p docs/.binder

    - name: Ficheros de configuracion
      run: |
        emacs --batch org-publish.org -l org -f org-babel-tangle

    - name: Execute Makefile notebooksYslides
      run: |
        set -e
        make notebooksYslides

    - name: Inspección tras notebooksYslides
      run: |
        echo "Contenido de ./Lecciones-tmp:"
        find ./Lecciones-tmp
        echo "Contenido de ./docs:"
        find ./docs

    - name: Execute Makefile practicas
      run: |
        set -e
        make practicas
        echo "Contenido de ./Practicas-tmp:"
        find ./Practicas-tmp

    - name: Execute Makefile calendario
      run: |
        set -e
        make calendario

    - name: Execute Makefile publicacion-lecciones
      run: |
        set -e
        make publicacion-lecciones

    - name: Execute Makefile publicacion-practicas
      run: |
        set -e
        make publicacion-practicas

    - name: Execute Makefile publicacion
      run: |
        set -e
        make publicacion

    - name: Comprobar contenido de docs antes de deploy
      run: |
        echo "Contenido de docs antes de deploy:"
        ls -la docs

    - name: Deploy docs/ a gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.NUEVO_TOKEN_CLASSIC_HASTA_JULIO_2026 }}
        publish_dir: ./docs
        publish_branch: gh-pages
#        force_orphan: true
#        allow_empty_commit: true
#+END_SRC
# NUEVO_TOKEN_CLASSIC_HASTA_JULIO_2026

** Aclaraciones

**** tlmgr
Scimax intenta usar ~tlmgr~ para instalar paquetes de $\LaTeX{}$, pero =Actions= de =GitHub= no lo permite. Las medidas tomadas para evitar este problema han sido 
1. Al ejecutarse ~.github/workflows/build.yml~ en GitHub Actions se crea un fichero =~/.emacs.d/no-tlmgr.el= con el siguiente contenido
   #+BEGIN_SRC 
(setq system-packages-use-sudo nil)
(setq TeX-install-font-lock nil)
   #+END_SRC
   así, al publicar los ficheros, podemos llamar a scimax del siguiente modo
   #+BEGIN_SRC 
emacs --batch \
  --load ~/.emacs.d/no-tlmgr.el \
  --load ~/Software/scimax/init.el \
  -l publica.el
   #+END_SRC
2. Además en ~.github/workflows/build.yml~ he añadido
   #+BEGIN_SRC 
    - name: Disable tlmgr (prevent accidental calls)
      run: sudo mv /usr/bin/tlmgr /usr/bin/tlmgr.disabled || true
   #+END_SRC

Quizá sea suficiente solo con esto segundo. Pero si quito el fichero =~/.emacs.d/no-tlmgr.el=, también he de omitirlo en las llamadas a emacs usando scimax (como así funciona... así se queda).

*** Consulta a Copilot sobre la generación de figuras

Tuve dificultades para que la ejecución en GitHub Actions de los de los cuadernos electrónicos de Scimax creara las figuras. A continuación copio mi consulta a copilot: 

#+BEGIN_QUOTE
-----
-----
*/Consulta/*:
/Anteriormente faltaba por instalar el paquete dvipng. Una vez instalado dvipng, el bloque de código/:

#+BEGIN_SRC jupyter-python :results file :exports results
plt.plot([1,2,3],[4,5,6])
plt.savefig("img/prueba_action.png")
"img/prueba_action.png"
#+END_SRC

/ha creado correctamente el fichero "img/prueba_action.png" con la figura. Sin embargo, el bloque/

#+BEGIN_SRC jupyter-python :results file :file ./img/lecc01/PIB_UEM.png
df1.plot(x='obs',xlabel='',figsize=(15,4)).set_title('PIB zona euro',fontsize=18)
#+END_SRC

/no ha creado el fichero ./img/lecc01/PIB_UEM.png con su correspondiente figura./
-----
-----
#+END_QUOTE

¡Excelente que la instalación de dvipng haya solucionado la generación de imágenes para el primer bloque!  
Ahora, pasemos a analizar por qué el segundo bloque *no genera* el archivo `./img/lecc01/PIB_UEM.png`.

-----

**** Diagnóstico y causas probables

***** 1. Diferencia clave entre ambos bloques

- *Bloque que funciona:*

  #+BEGIN_SRC org
  #+BEGIN_SRC jupyter-python :results file :exports results
  plt.plot([1,2,3],[4,5,6])
  plt.savefig("img/prueba_action.png")
  "img/prueba_action.png"
  #+END_SRC
  #+END_SRC

  - Aquí, tú generas la figura y la guardas explícitamente con `plt.savefig()`, y luego devuelves el nombre del archivo en la última línea.

- *Bloque que falla:*

  #+BEGIN_SRC org
  #+BEGIN_SRC jupyter-python :results file :file ./img/lecc01/PIB_UEM.png
  df1.plot(x='obs',xlabel='',figsize=(15,4)).set_title('PIB zona euro',fontsize=18)
  #+END_SRC
  #+END_SRC

  - Aquí confías en que org-babel/jupyter-python guardará automáticamente la figura en `:file`, pero el método pandas `df.plot()` *no guarda ni devuelve* el archivo.

***** 2. ¿Por qué falla el segundo bloque?

- El argumento `:file ./img/lecc01/PIB_UEM.png` espera que el último comando del bloque *guarde la imagen en ese path* (o devuelva una figura que org/jupyter pueda guardar ahí).
- El método `df1.plot(...).set_title(...)` crea y modifica una figura activa, pero *no la guarda*.
- Si usas solo `set_title()`, no hay ninguna instrucción para guardar el gráfico.
- Por defecto, ni org-babel ni jupyter-python pueden adivinar que la figura debe ser guardada en ese path si no se lo indicas de forma explícita.

-----

**** Solución recomendada

*Debes guardar la figura manualmente al path especificado*, y devolver ese path como resultado del bloque.

***** Forma correcta:

#+BEGIN_SRC jupyter-python :results file :file ./img/lecc01/PIB_UEM.png
ax = df1.plot(x='obs', xlabel='', figsize=(15,4))
ax.set_title('PIB zona euro', fontsize=18)
import matplotlib.pyplot as plt
plt.savefig("./img/lecc01/PIB_UEM.png")
"./img/lecc01/PIB_UEM.png"
#+END_SRC

- Esto asegura que la imagen se guarda donde deseas y que el bloque devuelve el path correcto para que org-babel inserte la imagen en el documento.

***** Alternativas

- Si usas solo `:results file` sin `:file`, puedes devolver el nombre del archivo en la última línea.
- Siempre asegúrate de llamar a `plt.savefig()` *después* de crear el gráfico.

-----

**** Resumen

- El bloque con `plt.savefig(...)` funciona porque guarda explícitamente la imagen.
- El bloque con pandas `plot` y solo `set_title()` *NO guarda la imagen*; debes añadir `plt.savefig()` y devolver el path.
- Así, org-babel/jupyter-python incrustará correctamente la imagen en el documento exportado.

-----

#+BEGIN_QUOTE
-----
-----
*/Consulta/*:
/Sin embargo. Cuando ejecuto localmente el fichero org sí se crean las figuras en mi disco. ¿Hay algún modo de que también se creen con Actions sin modificar los bloques? Es decir, ¿hay algún modo de que funcionen tal y como están ahora mismo?/
-----
-----
#+END_QUOTE

¡Esta es una pregunta muy frecuente al usar org-babel/jupyter en entornos CI/CD!  
La diferencia entre tu entorno local y GitHub Actions suele deberse a *la configuración del entorno gráfico* y de *matplotlib*.

-----

**** ¿Por qué funciona localmente pero no en Actions?

- *Localmente*, matplotlib tiene acceso a un entorno gráfico (X11, Wayland, etc.) y suele usar un backend como `TkAgg`, `Qt5Agg`,…
- *En GitHub Actions* (o cualquier entorno headless), *matplotlib no tiene acceso a un display* y por defecto puede intentar usar un backend que requiere uno, lo que impide guardar imágenes.

***** Backend headless necesario

Para guardar imágenes sin display, *matplotlib debe usar un backend como "Agg"*.

-----

**** Solución: Forzar el backend "Agg" para matplotlib

Esto se puede hacer *sin modificar los bloques* añadiendo una configuración previa en tu flujo de trabajo o al comienzo de la ejecución.

***** Opción 1: Variable de entorno en el workflow

Añade esto antes de ejecutar Emacs en tu `build.yml`:

#+BEGIN_SRC yaml
- name: Set MPLBACKEND (matplotlib)
  run: echo "MPLBACKEND=Agg" >> $GITHUB_ENV
#+END_SRC

Matplotlib detectará esto y usará el backend adecuado.

***** Opción 2: Variable de entorno en shell

O directamente en el comando de ejecución:

#+BEGIN_SRC bash
MPLBACKEND=Agg emacs -Q -l ~/Software/scimax/init.el ./lecciones/Lecc01.org --batch ...
#+END_SRC

***** Opción 3: Configuración en Emacs/jupyter-python

Si puedes modificar la configuración de Emacs que se carga, añade a tu init.el o a la cabecera de los bloques:

#+BEGIN_SRC python
import matplotlib
matplotlib.use("Agg")
#+END_SRC

Pero esto requeriría modificar los bloques, que quieres evitar.

-----

**** Resumen

- *El problema*: matplotlib necesita el backend "Agg" para funcionar headless.
- *La solución sin modificar los bloques*: establece la variable de entorno `MPLBACKEND=Agg` en el workflow antes de ejecutar Emacs.
- *Así*, los bloques que generan imágenes funcionarán igual en Actions que localmente, *sin necesidad de cambiar el código de los bloques*.

-----
-----
-----
*/SOLUCIÓN FINALMENTE ADOPTADA/*:

El backend "Agg"  no me funcionó, por lo que opté por indicar explícitamente en el código de python el fichero donde se debe guardar cada figura.
-----
-----
-----


*** Consulta sobre los núcleos de Jupyter

Cuando ejecuto Actions en GitHub y Actions ejecuta un notebook de jupyter ¿En qué directorio lo hace? Me gustaria matar los procesos  python3 -m ipykernel_launcher tras ejecutar los notebooks

**** Respuesta

Cuando GitHub Actions ejecuta un notebook de Jupyter, lo hace en un entorno temporal que se crea para cada ejecución de la acción. Usualmente, el directorio de trabajo es el que se especifica en el archivo de configuración (`.yml`) de la acción, comúnmente en el directorio del repositorio.

Si deseas matar los procesos de Jupyter después de que se ejecute un notebook en GitHub Actions, puedes agregar un paso en tu flujo de trabajo (workflow) que use un comando como `pkill` para terminar los procesos de Jupyter, tal como:

```yaml
- name: Kill Jupyter processes
  run: pkill -f "python3 -m ipykernel_launcher"
```

Sin embargo, ten en cuenta que los entornos de GitHub Actions se eliminan después de que una ejecución finaliza, por lo que normalmente no es necesario matar procesos manualmente al final del trabajo.

*** GitHub tokens

Para solucionar el error de autenticación debido a un token de GitHub caducado y usar un nuevo token, sigue estos pasos:

1. Genera un nuevo personal access token (PAT)
Ve a tu perfil de GitHub > Settings > Developer settings > Personal access tokens.
Haz clic en “Generate new token”.
Selecciona los scopes necesarios. Para subir a GitHub Pages y realizar pushes, selecciona:
repo (para acceso completo a los repositorios privados/públicos)
workflow (si tu workflow lo requiere)
Copia el token generado (no podrás verlo de nuevo).


2. Guarda el nuevo token en los Secrets del repositorio
Ve al repositorio: https://github.com/mbujosab/Econometria-Aplicada
Settings > Secrets and variables > Actions.
Haz clic en “New repository secret”.
Nombra el secret, por ejemplo: GH_TOKEN o PERSONAL_TOKEN.
Pega el token generado y guarda.
3. Actualiza tu workflow para usar el nuevo token
En tu archivo .github/workflows/build.yml (o el que corresponda), asegúrate de que el paso que hace git push o usa el token esté así:

YAML
- name: Push to GitHub Pages
  run: git push origin gh-pages
  env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # O el nombre que hayas puesto
O, si usas una acción como peaceiris/actions-gh-pages:

YAML
- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GH_TOKEN }}
4. Confirma que el token tiene los permisos adecuados
El token debe tener acceso de escritura al repo.
Si usas una acción (como actions/checkout o actions-gh-pages), asegúrate de pasar el secret correcto.



* Script =publica.el= de elisp para publicar las lecciones con formato =.org= como ficheros con formato =pdf= y ~html~

Este script transforma los ficheros org de las lecciones en pdfs y htmls. 

#+BEGIN_SRC  emacs-lisp :tangle publica.el :results silent
;;; publica.el --- Publicación HTML y PDF para el repositorio 

(require 'ox-publish)

(setq org-confirm-babel-evaluate nil
      org-export-with-broken-links t
      org-html-validation-link nil
      org-html-head-include-scripts nil
      org-html-head-include-default-style nil)

(defun my-org-latex-publish-to-pdf (plist filename pub-dir)
  "Publica un archivo Org como PDF tras ejecutar bloques de código."
  (message "Exportando a PDF: %s" filename)
  (with-current-buffer (find-file-noselect filename)
    (org-babel-execute-buffer)
    (sleep-for 25)
    (save-buffer)
    (org-latex-publish-to-pdf plist filename pub-dir)))

;; (defun my-org-html-publish-to-html (plist filename pub-dir)
;;   "Publica un archivo Org como PDF tras ejecutar bloques de código."
;;   (message "Exportando a html: %s" filename)
;;   (with-current-buffer (find-file-noselect filename)
;;     (org-babel-execute-buffer)
;;     (sleep-for 20)
;;     (org-html-publish-to-html plist filename pub-dir)))

(let* ((base-directory "./"))
  (setq org-publish-project-alist
        (append org-publish-project-alist
                `(("index"
                   :base-directory ,base-directory
                   :base-extension "org"
                   :publishing-directory ,(concat base-directory "docs")
                   :exclude "Calendario\\|org-lessons\\|org-practicas\\|docs\\|Lecciones-tmp\\|Practicas-tmp\\|org-publish.org\\|README.org\\|CriteriosEvaluacion.org\\datos"
                   :recursive t
                   :publishing-function org-html-publish-to-html
                   :auto-preamble t
                   :auto-sitemap nil
                   :with-author nil
                   :with-creator nil
                   :with-toc t
                   :section-numbers nil)

                  ("pdf"
                   :base-directory "./Lecciones-tmp/"
                   :base-extension "org"
                   :publishing-directory ,(concat base-directory "docs/Lecciones-pdf")
                   :exclude "README.org\\|sitemap.org\\datos"
                   :recursive t
                   :auto-sitemap nil
                   :publishing-function my-org-latex-publish-to-pdf
                   :auto-preamble t)
		  
                  ("html"
                   :base-directory  "./Lecciones-tmp/"
                   :base-extension "org"
                   :publishing-directory ,(concat base-directory "docs/Lecciones-html")
                   :exclude "README.org\\datos"
                   :recursive t
                   :publishing-function org-html-publish-to-html ; my-org-html-publish-to-html ; 
                   :auto-preamble t
                   :auto-sitemap t
                   :with-author nil
                   :with-creator nil
                   :with-toc t
                   :section-numbers nil)

                  ("static-index"
                   :base-directory ,base-directory
                   :base-extension "css\\|js\\|png\\|jpg\\|gif\\|dat\\|mov\\|txt\\|svg\\|aiff\\|inp"
                   :publishing-directory ,(concat base-directory "docs")
                   :exclude "src\\|Calendario\\|org-lessons\\|org-practicas\\|Lecciones-tmp\\|Practicas-tmp\\|docs\\|org-publish.*\\|README.org\\|CriteriosEvaluacion.org\\datos"
                   :recursive t
                   :publishing-function org-publish-attachment)

                  ("web-repositorio" :components ("index" "pdf" "html" "static-index")))))

  (message "🟢 Iniciando publicación del índice (web-repositorio)...")
  (org-publish "web-repositorio" t)
  (message "✅ Publicación del índice completada."))

#+END_SRC

# (unless (file-directory-p "logs")
#   (make-directory "logs"))
# (with-temp-file "logs/publica.log"
#   (insert (format "Publicado el %s\n" (current-time-string))))

Podemos chequear la versión local ejecutando en emacs el siguiente bloque

#+BEGIN_SRC emacs-lisp :results silent
(browse-url "docs/index.html")
#+END_SRC


* Script =publica-practicas.el= de elisp para publicar las prácticas con formato =.org= como ficheros con formato =pdf= y ~html~

Este script transforma los ficheros org de las lecciones en pdfs y htmls. 

#+BEGIN_SRC  emacs-lisp :tangle publica-practicas.el :results silent
;;; publica.el --- Publicación HTML y PDF de las prácticas para el repositorio


;; Lo siguiente es para que se vean en pdf los bloques de código hanls
;; Añade "listings" a org-latex-packages-alist
(add-to-list 'org-latex-packages-alist '("" "listings"))
;; Establece 'listings como valor para org-latex-listings
(setq org-latex-listings 'listings)
;(setq org-latex-listings 'minted)


(require 'ox-publish)

(setq org-confirm-babel-evaluate nil
      org-export-with-broken-links t
      org-html-validation-link nil
      org-html-head-include-scripts nil
      org-html-head-include-default-style nil)

(defun my-org-latex-publish-to-pdf (plist filename pub-dir)
  "Publica un archivo Org como PDF tras ejecutar bloques de código."
  (message "Exportando a PDF: %s" filename)
  (with-current-buffer (find-file-noselect filename)
    ;(org-babel-execute-buffer)
    ;(org-latex-export-to-pdf)
    (org-latex-publish-to-pdf plist filename pub-dir)))

(let* ((base-directory "./"))
  (setq org-publish-project-alist
        (append org-publish-project-alist
                `(("index"
                   :base-directory ,base-directory
                   :base-extension "org"
                   :publishing-directory ,(concat base-directory "docs")
                   :exclude "src\\|Calendario\\|org-lessons\\|org-practicas\\|docs\\|Lecciones-tmp\\|Practicas-tmp\\datos"
                   :recursive nil
                   :publishing-function org-html-publish-to-html
                   :auto-preamble t
                   :auto-sitemap nil
                   :with-author nil
                   :with-creator nil
                   :with-toc t
                   :section-numbers nil)

                  ("practicas-html"
                   :base-directory  "./Practicas-tmp/"
                   :base-extension "org"
                   :publishing-directory ,(concat base-directory "docs/Practicas-html")
                   :exclude "datos"
                   :recursive t
                   :publishing-function org-html-publish-to-html
                   :auto-preamble t
                   :auto-sitemap t
                   :with-author nil
                   :with-creator nil
                   :with-toc t
                   :section-numbers nil)

                  ("practicas-pdf"
                   :base-directory "./Practicas-tmp/"
                   :base-extension "org"
                   :publishing-directory ,(concat base-directory "docs/Practicas-pdf")
                   :exclude "datos\\|sitemap.org"
                   :recursive t
                   :auto-sitemap nil
                   :publishing-function my-org-latex-publish-to-pdf
                   :auto-preamble t)

                  ("practicas-static-index"
                   :base-directory "./Practicas-tmp/"
                   :base-extension "css\\|js\\|png\\|jpg\\|gif\\|dat\\|mov\\|txt\\|svg\\|aiff\\|inp"
                   :publishing-directory ,(concat base-directory "docs/Practicas-html")
                   :exclude "datos\\|hansl.tex"
                   :recursive t
                   :publishing-function org-publish-attachment)

                  ("web-repositorio" :components ("index" "practicas-html" "practicas-pdf" "practicas-static-index")))))

  (message "🟢 Iniciando publicación del índice (web-repositorio)...")
  (org-publish "web-repositorio" t)
  (message "✅ Publicación del índice completada."))

#+END_SRC


* slides para GitHubpages

Esta es la configuración para convertir los Notebooks de Jupyter en slides:
#+BEGIN_SRC python :tangle mycfg-GitHubPages.py
c = get_config()

c.SlidesExporter.reveal_theme = 'solarized'
c.SlidesExporter.reveal_scroll = True
c.SlidesExporter.language_code = 'es'

c.SlidesExporter.mathjax_url = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"

c.SlidesExporter.jquery_url = "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"

c.SlidesExporter.require_js_url = "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js"
#+END_SRC


[[https://nbconvert.readthedocs.io/en/latest/config_options.html][Configuración para nbconvert]] (las slides usan ficheros de la web para poder funcionar en GitHubPages)

[[https://dbafromthecold.com/2021/02/21/creating-presentations-with-reveal-and-github-pages/][creating-presentations-with-reveal-and-github-pages]]

https://github.com/RichardAfolabi/Presentation_js

https://emasuriano.com/til/2024-07-01-create-presentations-from-notebook/

https://github.com/yjwen/org-reveal
https://github.com/hexmode/ox-reveal


* Directorio =.binder= para MyBinder

** Fichero =environment.yml= 

Dado que los notebooks del curso emplean algunos módulos de python, la ejecución online en [[https://mybinder.org/][MyBinder]] de los correspondientes Notebooks de Jupyter requiere de la creación de un fichero que indique las dependencias necesarias para que se instale el software necesario (creo que =defaults= instala el latex necesario para los gráficos). 

#+BEGIN_SRC yml :tangle docs/.binder/environment.yml
name: binder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - sympy
  - statsmodels
  - scipy
  - pillow  # Biblioteca necesaria para manipulación de imágenes (grafico arcoiris)
  - requests>=2.31,<3
  - urllib3>=2,<3
  - charset-normalizer>=3,<4
  - pip:
      - dataframe_image
#+END_SRC


** Fichero =apt.txt= 

Algunos gráficos de los notebooks usan \LaTeX{}. Este fichero indica a MyBinder qué paquetes debe instalar para cubrir las dependencias.

#+BEGIN_SRC text :tangle docs/.binder/apt.txt
texlive
texlive-latex-extra
texlive-fonts-recommended
texlive-fonts-extra
dvipng
cm-super
#+END_SRC



