name: binder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - sympy
  - statsmodels
  - scipy
  - pillow  # Biblioteca necesaria para manipulación de imágenes (grafico arcoiris)
  - requests>=2.32,<3
  - urllib3>=2,<3
  - charset-normalizer>=3,<4
  - pip:
      - dataframe_image
